name: CI

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      ACTIONS_ALLOW_UNSECURE_COMMANDS: true
  
    steps:
      - uses: actions/checkout@v2
      
      - name: Setup Node.js enviroment
        uses: actions/setup-node@v1.4.2
        with:
          node-version: 14.x
          
      - name: Install dependencies
        run: yarn
        
      - name: Run build
        run: yarn babel:build
      
      - name: Copy dist to Digital Ocean
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          key: ${{ secrets.SSH_KEY }}
          source: ".,!node_modules"
          target: "~/app/stone-marvel-api"
          
      - name: Install Dependencies on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/stone-marvel-api
            yarn
            
      - name: Run migrations on Digital Ocean
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ~/app/stone-marvel-api
            .node_modules/.bin/typeorm migration:run
            
      - name: Restarting server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          port: ${{ secrets.SSH_PORT }}
          script: pm2 restart marvel-api

      
